[package]
name = "dojo_shooter"
version = "0.1.0"
cairo-version = "1.1.0"


[cairo]
sierra-replace-ids = true

[dependencies]
# dojo_core = { git = "https://github.com/dojoengine/dojo", version = "0.1.0"}
dojo_core = { git = "https://github.com/dojoengine/dojo", rev = "1e471b4019233b77bde10b4e02bfc167b7904937" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# rpc_url = "http://localhost:5050/"
# rpc_url = "http://54.252.157.63:5050"
# world_address = "0x7f1d6c1b15e03673062d8356dc1174d5d85c310479ec49fe781e8bf89e4c4f8"
